from typing import Protocol

from app.domain.entities import ActivityEvent, ExtractionBatch, Project, RawEntry, Task


class RawEntryRepository(Protocol):
    def add(self, entry: RawEntry) -> RawEntry: ...

    def get(self, entry_id: str) -> RawEntry | None: ...

    def list_all(self) -> list[RawEntry]: ...


class ExtractionBatchRepository(Protocol):
    def add(self, batch: ExtractionBatch) -> ExtractionBatch: ...

    def list_for_entry(self, raw_entry_id: str) -> list[ExtractionBatch]: ...


class TaskRepository(Protocol):
    def add(self, task: Task) -> Task: ...

    def get(self, task_id: str) -> Task | None: ...

    def list_active(self) -> list[Task]: ...

    def list_all(self) -> list[Task]: ...

    def update(self, task: Task) -> Task: ...


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...

    def list_all(self) -> list[Project]: ...

    def get(self, project_id: str) -> Project | None: ...


class ActivityEventRepository(Protocol):
    def add(self, event: ActivityEvent) -> ActivityEvent: ...

    def list_recent(self, limit: int = 50) -> list[ActivityEvent]: ...


class SettingsRepository(Protocol):
    def get_local_settings(self) -> dict[str, str | bool | None]: ...

    def save_local_settings(self, values: dict[str, str | bool | None]) -> dict[str, str | bool | None]: ...
